# -*- coding: utf-8 -*-
"""Language Identification using Hugging Face Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQV1slzM_SZxqwBh2LQ_DSBuFxOVDXtZ
"""

# Install the Hugging Face Transformers library
!pip install transformers

# Import the necessary library
from transformers import pipeline

# Load the XLM-Roberta model for language identification
model_name = "papluca/xlm-roberta-base-language-detection"
classifier = pipeline("text-classification", model=model_name)

# Sample texts
texts = [
    "This is an English text.",
    "Este es un texto en español.",
    "Ceci est un texte en français.",
    "Dies ist ein deutscher Text."
]

# Classify the texts
results = classifier(texts)

# Print the results
for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Prediction: {result['label']}, Score: {result['score']}\n")